---
shared:
  mailer: &shared_mailer
    submit: &shared_submit_mailer
      subject: "Nous avons bien re√ßu votre demande d‚Äôhabilitation"
    validate: &shared_validate_mailer
      subject: "Votre habilitation a √©t√© valid√©e"
    request_changes: &shared_request_changes_mailer
      subject: "Votre demande d‚Äôhabilitation requiert des modifications"
    refuse: &shared_refuse_mailer
      subject: "Votre habilitation a √©t√© refus√©e"
    revoke: &shared_revoke_mailer
      subject: "Votre habilitation a √©t√© r√©voqu√©e"
    notify_submitted: &shared_notify_submitted_mailer
      subject: "Nouvelle demande d‚Äôhabilitation sur DataPass"
    create: &shared_create_mailer
      subject: "Votre demande d‚Äôhabilitation a √©t√© enregistr√©e"
    notify: &shared_notify_mailer
      subject: "Vous avez un nouveau message concernant votre demande d‚Äôhabilitation"

franceconnect:
  label: FranceConnect
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer
  reply_to: support.partenaires@franceconnect.gouv.fr

api_particulier:
  label: API Particulier
  support_email: contact@particulier.api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_sandbox:
  label: API Imp√¥t particulier (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_production:
  label: API Imp√¥t particulier (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_fc_sandbox:
  label: API Imp√¥t particulier (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_fc_production:
  label: API Imp√¥t particulier (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_r2p_sandbox:
  label: API R2P (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_r2p_production:
  label: API R2P (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ficoba_sandbox:
  label: API FICOBA (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ficoba_production:
  label: API FICOBA (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_droits_cnam:
  label: API Droits CNAM
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_entreprise:
  label: API Entreprise
  api_manager_label: dashboard API Entreprise
  support_email: support@entreprise.api.gouv.fr
  mailer:
    <<: *shared_mailer
    create:
      subject: "üíæ Le brouillon de votre demande d‚Äôhabilitation a bien √©t√© enregistr√©"
    submit:
      subject: "üì¨ Votre demande d‚Äôhabilitation a bien √©t√© re√ßue par API Entreprise"
    request_changes:
      subject: "‚úíÔ∏è Votre demande d‚Äôhabilitation requiert des modifications"
    validate:
      subject: "‚úÖ Votre habilitation √† l'API Entreprise a √©t√© valid√©e"
    refuse:
      subject: "üö´ Votre habilitation √† l‚ÄôAPI Entreprise a √©t√© refus√©e"

le_taxi:
  label: le.Taxi
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

cartobio:
  label: CartoBio
  support_email: cartobio@beta.gouv.fr
  mailer: *shared_mailer

aidants_connect:
  label: Aidants Connect
  support_email: contact@aidantsconnect.beta.gouv.fr
  mailer: *shared_mailer

api_service_national:
  label: API Service National
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_hermes_sandbox:
  label: API Hermes (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_hermes_production:
  label: API Hermes (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

hubee_portail:
  label: Portail HubEE
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer
  reply_to: dgs-certdc@sante.gouv.fr

hubee_portail_dila:
  label: Portail HubEE
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer
  reply_to: support-partenaires@service-public.fr

api_pro_sante_connect:
  label: API Pro Sant√© Connect
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_indemnites_journalieres_cnam:
  label: API Indemnit√©s Journali√®res (CNAM)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_e_contacts_sandbox:
  label: API E-Contacts (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_e_contacts_production:
  label: API E-Contacts (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_opale_sandbox:
  label: API OPALE (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_opale_production:
  label: API OPALE (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_mire_sandbox:
  label: API MIRE (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_mire_production:
  label: API MIRE (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ocfi_sandbox:
  label: API OCFI (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ocfi_production:
  label: API OCFI (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_e_pro_sandbox:
  label: API E-PRO (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_e_pro_production:
  label: API E-PRO (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_robf_sandbox:
  label: API ROBF (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_robf_production:
  label: API ROBF (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_cpr_pro_sandbox:
  label: API CPR PRO - ADELIE (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_cpr_pro_production:
  label: API CPR PRO - ADELIE (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_infinoe_sandbox:
  label: API INFINOE (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_infinoe_production:
  label: API INFINOE (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_declaration_auto_entrepreneur:
  label: API Tierce D√©claration auto-entrepreneur
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_tiers_de_prestation:
  label: API Tiers de prestation
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_declaration_cesu:
  label: API Tierce D√©claration CESU
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ensu_documents_sandbox:
  label: API ENSU Documents (Bac √† sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ensu_documents_production:
  label: API ENSU Documents (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_histovec:
  label: API Historique d‚Äôun v√©hicule
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ingres:
  label: API INGRES
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_prestations_sociales:
  label: API prestations sociales
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_prestations_sociales_fc:
  label: API prestations sociales (FC)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_statut_etudiant:
  label: API Statut √©tudiant
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_statut_demandeur_emploi:
  label: API statut demandeur d‚Äôemploi
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_captchetat:
  label: API CaptchEtat
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_statut_etudiant_boursier:
  label: API Statut √©tudiant boursier
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_indemnisation_pole_emploi:
  label: API Indemnisation P√¥le emploi
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_declaration_embauche:
  label: API D√©claration pr√©alable √† l‚Äôembauche
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer
