- hosts: datapass-front,datapass-back,api-auth
  become: true
  roles:
    - app-user
    - role: team-ssh-keys
      tags: team-ssh-keys
    - role: ufw
      tags: ufw
    - role: nginx
      tags: nginx

- hosts: datapass-front
  become: true
  roles:
    - role: ansible-role-nodejs
      nodejs_version: 16.x
      tags: nodejs

- hosts: api-auth
  become: true
  roles:
    - role: ansible-role-nodejs
      nodejs_version: 12.x
      tags: nodejs

- hosts: datapass-back
  become: true
  roles:
    - role: ruby
      tags: ruby
    - role: redis
      tags: redis
    - role: ssl
      server_name: "{{ back_domain_name }}"
      tags: ssl
    - role: postgres
      pg_user: back
      pg_password: "{{ back_pg_password }}"
      pg_database: signup-back
    - role: backup-script
      backup_user: postgres
      store_identifier: signup-back
      backup_type: postgresql
      frequency: daily
      tags: backup-script
      when: disable_backup is not defined
    - role: backup-script
      backup_user: signup
      store_identifier: /opt/apps/signup-back/uploads
      frequency: weekly
      backup_type: file
      tags: backup-script
      when: disable_backup is not defined
    - role: rails-app
      app_service_name: signup-back
      server_name: "{{ back_domain_name }}"
      app_port: 3000
      pg_user: back
      pg_password: "{{ back_pg_password }}"
      pg_database: signup-back
      devise_secret: "{{ back_devise_secret }}"
      secret_key_base: "{{ back_secret_key_base }}"
      env_var:
        RUBYOPT: "'-W0'"
        SERVER_NAME: "{{ inventory_hostname }}"
        PORT: "{{ app_port }}"
        FRONT_HOST: "{{ front_host }}"
        ALLOWED_ORIGINS: "{{ allowed_origins }}"
        BACK_HOST: "{{ back_host }}"
        OAUTH_HOST: "{{ oauth_host }}"
        DEVISE_SECRET: "{{ devise_secret }}"
        SECRET_KEY_BASE: "{{ secret_key_base }}"
        RGPD_CONTACT_ERROR_HOOK_ID: "{{ rgpd_contact_error_hook_id }}"
        SENTRY_DSN: "{{ sentry_dsn | default('') }}"
        PG_USER: "{{ pg_user }}"
        PG_PASSWORD: "{{ pg_password }}"
        PG_DATABASE: "{{ pg_database }}"
        DATAPASS_OAUTH_CLIENT_ID: "{{ datapass_oauth_client_id }}"
        DATAPASS_OAUTH_CLIENT_SECRET: "{{ datapass_oauth_client_secret }}"
        DISABLE_API_PARTICULIER_BRIDGE: "{{ disable_api_particulier_bridge | default('') }}"
        API_PARTICULIER_HOST: "{{ api_particulier_host }}"
        API_PARTICULIER_API_KEY: "{{ api_particulier_api_key }}"
        DISABLE_FRANCECONNECT_BRIDGE: "{{ disable_franceconnect_bridge | default('') }}"
        FRANCECONNECT_PARTICULIER_HOST: "{{ franceconnect_particulier_host }}"
        FRANCECONNECT_PARTICULIER_API_KEY: "{{ franceconnect_particulier_api_key }}"
        DISABLE_API_ENTREPRISE_BRIDGE: "{{ disable_api_entreprise_bridge | default('') }}"
        API_ENTREPRISE_HOST: "{{ api_entreprise_host }}"
        API_ENTREPRISE_API_KEY: "{{ api_entreprise_api_key }}"
        API_ENTREPRISE_WEBHOOK_URL: "{{ api_entreprise_webhook_url }}"
        API_ENTREPRISE_VERIFY_TOKEN: "{{ api_entreprise_verify_token }}"
        DISABLE_AIDANTS_CONNECT_BRIDGE: "{{ disable_aidants_connect_bridge | default('') }}"
        AIDANTS_CONNECT_HOST: "{{ aidants_connect_host }}"
        AIDANTS_CONNECT_API_KEY: "{{ aidants_connect_api_key }}"
        DISABLE_API_IMPOT_PARTICULIER_BRIDGE: "{{ disable_api_impot_particulier_bridge | default('') }}"
        DISABLE_API_DROITS_CNAM_BRIDGE: "{{ disable_api_droits_cnam_bridge | default('') }}"
        DISABLE_API_INDEMNITES_JOURNALIERES_CNAM_BRIDGE: "{{ disable_api_indemnites_journalieres_cnam_bridge | default('') }}"
        DISABLE_HUBEE_PORTAIL_BRIDGE: "{{ disable_hubee_portail_bridge | default('') }}"
        HUBEE_HOST: "{{ hubee_host }}"
        HUBEE_AUTH_URL: "{{ hubee_auth_url }}"
        HUBEE_CLIENT_ID: "{{ hubee_client_id }}"
        HUBEE_CLIENT_SECRET: "{{ hubee_client_secret }}"
        MAILJET_API_KEY: "{{ mailjet_api_key }}"
        MAILJET_SECRET_KEY: "{{ mailjet_secret_key }}"
        SENDINBLUE_API_KEY: "{{ sendinblue_api_key }}"
        DO_NOT_SEND_MAIL: "{{ do_not_send_mail | default('') }}"
      tags:
        - back
        - app-config

- hosts: datapass-front
  become: true
  roles:
    - role: ssl
      server_name: "{{ front_domain_name }}"
      tags: ssl
    - role: ssl
      server_name: "{{ former_front_domain_name }}"
      tags: ssl
    - role: react-app
      app_service_name: signup-front
      server_name: "{{ front_domain_name }}"
      permanent_redirect_rules:
        - source_pattern: "= /api-impot-particulier"
          destination_path: "/api-impot-particulier-fc-sandbox"
        - source_pattern: "= /api-impot-particulier-step2"
          destination_path: "/api-impot-particulier-fc-production"
        - source_pattern: "~ ^/le-taxi/([0-9]+)"
          destination_path: "/authorization-request/$1"
        - source_pattern: "~ ^/hubee/([0-9]+)"
          destination_path: "/hubee-portail/$1"
      tags:
        - front
        - app-config
    - role: domain-redirection
      alternative_domain: "{{ former_front_domain_name }}"
      current_domain: "{{ front_domain_name }}"
      tags: domain-redirection

- hosts: api-auth
  become: true
  roles:
    - role: ssl
      server_name: "{{ api_auth_domain_name }}"
      tags: ssl
    - role: postgres
      pg_user: api-auth
      pg_password: "{{ api_auth_pg_password }}"
      pg_database: api-auth
    - role: backup-script
      backup_user: api-auth
      store_identifier: api-auth
      backup_type: postgresql
      frequency: daily
      tags: backup-script
      when: disable_backup is not defined
    - role: redis
      tags: redis
    - role: node-app
      app_service_name: api-auth
      server_name: "{{ api_auth_domain_name }}"
      app_port: 3000
      env_var:
        PGUSER: api-auth
        PGPASSWORD: "{{ api_auth_pg_password }}"
        PGDATABASE: api-auth
        PGPORT: 5432
        DATABASE_URL: "postgres://api-auth:{{ api_auth_pg_password }}@127.0.0.1:5432/api-auth"
        SENDINBLUE_API_KEY: "{{ sendinblue_api_key }}"
        API_AUTH_HOST: "https://{{ api_auth_domain_name }}"
        DO_NOT_SEND_MAIL: "{{ do_not_send_mail | default('') }}"
        SESSION_COOKIE_SECRET: "{{ session_cookie_secret }}"
      tags:
        - api-auth
        - app-config

- hosts: api-auth
  become: true
  roles:
    - role: app-user
      app_user: retool
      when: retool_ssh_key is defined
      tags: retool
    - role: team-ssh-keys
      app_user: retool
      team_ssh_keys:
        - "{{ retool_ssh_key }}"
      when: retool_ssh_key is defined
      tags: retool
