- name: create app directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  with_items:
    - /opt/apps
    - "/opt/apps/{{app_service_name}}"

- name: copy configuration file
  template:
    src: service.conf.j2
    dest: "/etc/{{app_service_name}}.conf"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0400
  notify: "restart service {{app_service_name}}"

- name: copy puma systemd file
  template:
    src: app.service.j2
    dest: "/etc/systemd/system/{{app_service_name}}.service"
  notify: "restart service {{app_service_name}}"

- name: copy sidekiq systemd file
  template:
    src: sidekiq.service.j2
    dest: "/etc/systemd/system/sidekiq-{{app_service_name}}.service"
  notify: "restart service sidekiq-{{app_service_name}}"

- name: enable services
  systemd:
    name: "{{app_service_name}}"
    daemon_reload: yes
    enabled: true

- lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{app_user}} ALL=NOPASSWD: /bin/systemctl restart {{app_service_name}}"
    validate: '/usr/sbin/visudo -cf %s'

- lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{app_user}} ALL=NOPASSWD: /bin/systemctl restart sidekiq-{{app_service_name}}"
    validate: '/usr/sbin/visudo -cf %s'

- name: configure nginx
  template:
    src: server.conf.j2
    dest: "/etc/nginx/sites-enabled/{{app_service_name}}"
  notify: restart nginx
