api_entreprise:
  label: API Entreprise
  api_manager_label: dashboard API Entreprise
  reply_to: support@entreprise.api.gouv.fr
  mailer:
    <<: *shared_mailer
    create:
      subject: "ðŸ’¾ Le brouillon de votre demande dâ€™habilitation a bien Ã©tÃ© enregistrÃ©"
    submit:
      subject: "ðŸ“¬ Votre demande dâ€™habilitation a bien Ã©tÃ© reÃ§ue par API Entreprise"
    request_changes:
      subject: "âœ’ï¸ Votre demande dâ€™habilitation requiert des modifications"
    validate:
      subject: "âœ… Votre habilitation Ã  l'API Entreprise a Ã©tÃ© validÃ©e"
    refuse:
      subject: "ðŸš« Votre habilitation Ã  lâ€™API Entreprise a Ã©tÃ© refusÃ©e"
    revoke:
      subject: "ðŸš« Votre habilitation Ã  lâ€™API Entreprise a Ã©tÃ© rÃ©voquÃ©e"
