---
- name: Ensure webroot exists
  file:
    path: "/etc/letsencrypt/live/{{ server_name }}"
    state: directory

- name: Generate self-signed certificates for {{ server_name }}
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ server_name }}" -days 3650 -keyout /etc/letsencrypt/live/{{ server_name }}/privkey.pem -out /etc/letsencrypt/live/{{ server_name }}/fullchain.pem -extensions v3_ca
  args:
    creates: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
  notify:
    - restart nginx
