---
- name: create app directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  with_items:
    - /opt/apps
    - "/opt/apps/{{app_service_name}}"
    - "/var/log/{{app_service_name}}"

- name: Ensure log file exists
  file:
    path: "{{ access_log_path }}"
    state: touch
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0644

- name: copy configuration file
  template:
    src: service.conf.j2
    dest: "/etc/{{app_service_name}}.conf"
  notify: "restart service {{app_service_name}}"

- name: copy systemd file
  template:
    src: app.service.j2
    dest: "/etc/systemd/system/{{app_service_name}}.service"
  notify: "restart service {{app_service_name}}"

- name: enable services
  systemd:
    name: "{{app_service_name}}"
    daemon_reload: yes
    enabled: true

- lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{app_user}} ALL=NOPASSWD: /bin/systemctl restart {{app_service_name}}"
    validate: '/usr/sbin/visudo -cf %s'

- name: enable logrotate
  template:
    src: logrotate-conf.j2
    dest: "/etc/logrotate.d/{{app_service_name}}"

- name: configure nginx
  template:
    src: server.conf.j2
    dest: "/etc/nginx/sites-enabled/{{app_service_name}}"
  notify: restart nginx

